### PR TITLE
Modify the Slicing Command

### PR DESCRIPTION
**Pull request by jamiehofer**
I am using version 1.2.9 of Slic3r and it will not work without using Perl because I pulled it straight from GitHub. I am not sure if this will break compatibility with released versions of Slic3r.

command will now be:

`perl "executable" --load "profile_path" -o "machinecode_path" "model_path"`

This successfully got rid of the issue of the GCODE's being only a few bytes and **only** containing:
`;Generated from [File name].stl [long string of garbage]`

Another way of doing this would be to set the path to:
`/home/pi/Slic3r/./slic3r.pl`

### CODE REVIEW

**Comment by foosel** [comment]
Hm.. this is actually something that should rather be solved either by modifying the command configuration so that it allows specifying the path to the script interpreter (`perl`) as the prefix or by fixing the [shebang line](https://en.wikipedia.org/wiki/Shebang_(Unix)) in the slic3r executable to reflect the proper perl executable (and also making sure it's executable in the first place through `chmod +x`).

Your proposed change would actually break it altogether in setups where "perl" is not on the path, with no way for the user to fix the situation again since it's hardcoded.

Could you shed some more light on the problem you faced, the steps you tried in solving it and also why there are changes to the profile.ini in this PR? Is/was `slic3r.pl` marked as executable and does the first line look like a valid shebang (I'd expect something like `#! /usr/bin/env perl`)?

**Comment by jamiehofer** [comment]
Perhaps a checkbox could be added in the Slic3r settings menu that would add the prefix for people who pull Slic3r from Github. I assume that all versions pulled from Github use Perl, correct?

**Comment by eyal0** [comment]
Can you figure out why the command doesn't work from the command-line without the perl prefix?  For me it works.  When I tried to run `./slic3r.pl`, I got this:

```
└──> ./slic3r.pl --version
1.31.6
```

I also cloned it straight from github.  Are you on a Linux system?  Maybe the version of perl run is different when you use a a leading `perl` vs not?

**Comment by jamiehofer** [comment]
@eyal0 Yup, Linux system. I don't remember that well but I think I pulled from the latest release on GitHub but I may have just pulled the latest.

**Comment by eyal0** [comment]
I also pulled latest and it works fine for me. If it's not working from the terminal either then the problem is your config. The shebang may point to the wrong installation of Perl or to a non-existent location.

Perhaps write your own slic3r.pl wrapper that is executable and use that? For the reasons that @foosel mentioned, adding perl into the command line doesn't make sense.

What error do you see from the CLI?

**Comment by eyal0** [comment]
Not reproducible.  Reopen this if you're still seeing the issue and want to debug it.

**Pull request closed without merging**
