### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by sfjuocekr**
Fixes using PrusaSlicer

### CODE REVIEW

**Comment by eyal0** [comment]
This will break old slic3r versions, right?

Can you put a version check into the code and then branch depending on the version?

**Comment by sfjuocekr** [comment]
Probably, I think a simple checkbox to mark the use  of PrusaSlicer would suffice in this case as well.

When the heat settles down I might look into it!

**Comment by eyal0** [comment]
I worry that no one will find the checkbox and I'll be getting more bug reports.  Why not just add a check in the code?  Just run, like slic3r --version, look at the output, and determine which arguments to use based on that?

**Comment by eyal0** [comment]
Fixed in #51

**Pull request closed without merging**
